package colaimpresion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author mariv
 */
public class Main extends javax.swing.JFrame {
    private Usuarios usuarios = new Usuarios();
    private TablaDeDispersion tabla = new TablaDeDispersion();
    private MonticuloBinario monticulo = new MonticuloBinario();
    private Cronometro tiempo = new Cronometro();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ManejoCola = new javax.swing.JButton();
        ManejoDocumentos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JTextField = new javax.swing.JButton();
        ManejoUsuarios = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        jLabel1.setText("PrintingTime");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen1.gif"))); // NOI18N
        jLabel3.setText("jLabel3");

        ManejoCola.setBackground(new java.awt.Color(153, 153, 255));
        ManejoCola.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ManejoCola.setText("Manejo de Cola de Impresion");
        ManejoCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManejoColaActionPerformed(evt);
            }
        });

        ManejoDocumentos.setBackground(new java.awt.Color(153, 153, 255));
        ManejoDocumentos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ManejoDocumentos.setText("Manejo de Documentos");
        ManejoDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManejoDocumentosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Webdings", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("'");

        jLabel7.setFont(new java.awt.Font("Webdings", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("'");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ManejoDocumentos)
                        .addGap(18, 18, 18)
                        .addComponent(ManejoCola))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManejoDocumentos)
                    .addComponent(ManejoCola))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTextField.setBackground(new java.awt.Color(255, 204, 204));
        JTextField.setFont(new java.awt.Font("Sana", 0, 14)); // NOI18N
        JTextField.setText("Cargar Archivo");
        JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 29));

        ManejoUsuarios.setBackground(new java.awt.Color(255, 204, 204));
        ManejoUsuarios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ManejoUsuarios.setText("Manejo de Usuarios");
        ManejoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManejoUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(ManejoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen3.gif"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 143, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen2.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen4.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldActionPerformed
        JFileChooser buscador = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV FILES", "csv");
        buscador.setFileFilter(filter);

        // Abrimos la ventana
        int seleccion = buscador.showOpenDialog(this);

        // Si el usuario acepta la opcion de archivo
        if (seleccion == JFileChooser.APPROVE_OPTION){
            // Selecciona el fichero
            File fichero = buscador.getSelectedFile( );

            String fileType = buscador.getTypeDescription(fichero);

            try (FileReader lector = new FileReader (fichero) ) {
                String contenido = "";
                int valor = lector.read( );

                while (valor != -1){
                    contenido += (char)valor;
                    valor = lector.read( );
                }

                if (contenido.contains("usuario,tipo") && (fileType.equals("Microsoft Excel Comma Separated Values File"))){
                    tabla = new TablaDeDispersion();
                    monticulo = new MonticuloBinario();
                    String [] divide = contenido.split("\n");
                    Usuarios usuarios = new Usuarios();
                    usuarios.CargarArchivo(divide);
                    this.usuarios = usuarios;
                    JOptionPane.showMessageDialog(null, "El archivo se ha cargado exitosamente ✅");

                } else {
                    JOptionPane.showMessageDialog(null, "ERROR!\nCargue un archivo valido");
                }

            } catch (Exception e){
                e.printStackTrace( );
            }
        }
    }//GEN-LAST:event_JTextFieldActionPerformed

    private void ManejoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManejoUsuariosActionPerformed
        if (usuarios.getNombres().length != 0){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    ManejoUsuarios manejo = new ManejoUsuarios();
                    manejo.setUsuarios(usuarios);
                    manejo.setTabla(tabla);
                    manejo.setMonticulo(monticulo);
                    manejo.setTiempo(tiempo);                  
                    manejo.LlenarboxPrioridadActionPerformed(evt);
                    manejo.LlenarboxActionPerformed(evt);
                    manejo.LlenarUsuariosActionPerformed(evt);
                    manejo.setVisible(true);
                }
            });

            // Ocultar esta interfaz
            this.setVisible(false);
        } else {
            int input = JOptionPane.showConfirmDialog(null, "\nLa lista de Usuarios esta vacia!\nDesea cargar el archivo predeterminado? ");
            
            if (input == 0){
                try{
                    FileReader lector = new FileReader ("usuarios.csv");
                    String contenido = "";
                    int valor = lector.read( );

                    while (valor != -1){
                        contenido += (char)valor;
                        valor = lector.read( );
                    }

                    String [] divide = contenido.split("\n");

                    File fichero = new File("usuarios.csv");
                    usuarios.CargarArchivo(divide);

                } catch (Exception e){
                    e.printStackTrace( );
                }
            } 
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManejoUsuarios manejo = new ManejoUsuarios();
                manejo.setUsuarios(usuarios);
                manejo.setTabla(tabla);
                manejo.setMonticulo(monticulo);
                manejo.setTiempo(tiempo);
                manejo.LlenarUsuariosActionPerformed(evt);
                manejo.LlenarboxPrioridadActionPerformed(evt);
                manejo.LlenarboxActionPerformed(evt);
                manejo.setVisible(true);
            }
            });

            // Ocultar esta interfaz
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_ManejoUsuariosActionPerformed

    private void ManejoDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManejoDocumentosActionPerformed
        if (usuarios.getNombres().length != 0){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManejoDocumentos manejo = new ManejoDocumentos();
                manejo.setUsuarios(usuarios);
                manejo.setTabla(tabla);
                manejo.setMonticulo(monticulo);
                manejo.setTiempo(tiempo);
                manejo.LlenarboxActionPerformed(evt);
                manejo.LlenarboxSizeActionPerformed(evt);
                manejo.LlenarboxTiposActionPerformed(evt);
                manejo.setVisible(true);
            }
        });

        // Ocultar esta interfaz
        this.setVisible(false);
        } else {
            int input = JOptionPane.showConfirmDialog(null, "\nLa lista de Usuarios esta vacia!\nDesea cargar el archivo predeterminado? ");
            
            if (input == 0){
                try{
                    FileReader lector = new FileReader ("usuarios.csv");
                    String contenido = "";
                    int valor = lector.read( );

                    while (valor != -1){
                        contenido += (char)valor;
                        valor = lector.read( );
                    }

                    String [] divide = contenido.split("\n");

                    File fichero = new File("usuarios.csv");
                    usuarios.CargarArchivo(divide);

                } catch (Exception e){
                    e.printStackTrace( );
                }
            }
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManejoDocumentos manejo = new ManejoDocumentos();
            manejo.setUsuarios(usuarios);
            manejo.setTabla(tabla);
            manejo.setMonticulo(monticulo);
            manejo.setTiempo(tiempo);
            manejo.LlenarboxActionPerformed(evt);
            manejo.LlenarboxSizeActionPerformed(evt);
            manejo.LlenarboxTiposActionPerformed(evt);
            manejo.setVisible(true);
            }
            });

            // Ocultar esta interfaz
            this.setVisible(false);
           
        }
    }//GEN-LAST:event_ManejoDocumentosActionPerformed

    private void ManejoColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManejoColaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManejoColaImpresion manejo = new ManejoColaImpresion();
                manejo.setUsuarios(usuarios);
                manejo.setTabla(tabla);
                manejo.setMonticulo(monticulo);
                manejo.setTiempo(tiempo);
                manejo.MostrarColaPActionPerformed(evt);
                manejo.setVisible(true);
            }
        });

        // Ocultar esta interfaz
        this.setVisible(false);
    }//GEN-LAST:event_ManejoColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public Usuarios getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public TablaDeDispersion getTabla() {
        return tabla;
    }

    public void setTabla(TablaDeDispersion tabla) {
        this.tabla = tabla;
    }

    public MonticuloBinario getMonticulo() {
        return monticulo;
    }

    public void setMonticulo(MonticuloBinario monticulo) {
        this.monticulo = monticulo;
    }

    public Cronometro getTiempo() {
        return tiempo;
    }

    public void setTiempo(Cronometro tiempo) {
        this.tiempo = tiempo;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JTextField;
    private javax.swing.JButton ManejoCola;
    private javax.swing.JButton ManejoDocumentos;
    private javax.swing.JButton ManejoUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}   
