package colaimpresion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
* Descripcion: Interfaz de Manejo Cola Impresion
* @autor: Maria Martinez
* @version: 20/11/23
*/
public class ManejoColaImpresion extends javax.swing.JFrame {
    private Usuarios usuarios;
    private TablaDeDispersion tabla = new TablaDeDispersion();
    private MonticuloBinario monticulo = new MonticuloBinario();
    private Cronometro tiempo = new Cronometro();
//    DefaultListModel modelo= new DefaultListModel();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Descripcion: Contructor de la interfaz Manejo Cola Impresion
     * @autor: Maria Martinez
     * @version: 20/11/23
     */
    public ManejoColaImpresion() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        String info [] = {"Nombre","Tipo","Tamaño"}; 
        modelo.setColumnIdentifiers(info);
        tablaUsuarios.setModel(modelo);
////        jList1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Return = new javax.swing.JButton();
        Titulo1 = new javax.swing.JLabel();
        Liberar = new javax.swing.JButton();
        MostrarArbol = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        Titulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Return.setBackground(new java.awt.Color(204, 255, 255));
        Return.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Return.setForeground(new java.awt.Color(0, 0, 51));
        Return.setText("<-");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 28, 50, -1));

        Titulo1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        Titulo1.setText("Cola de Impresión");
        getContentPane().add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 409, -1));

        Liberar.setBackground(new java.awt.Color(153, 153, 255));
        Liberar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Liberar.setText("Liberar");
        Liberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiberarActionPerformed(evt);
            }
        });
        getContentPane().add(Liberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 151, -1));

        MostrarArbol.setBackground(new java.awt.Color(153, 153, 255));
        MostrarArbol.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MostrarArbol.setText("Mostrar Arbol");
        MostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArbolActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        tablaUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaUsuarios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 430, 210));

        Titulo2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        Titulo2.setText("Documentos en cola");
        getContentPane().add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 360, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen5.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Descripcion: Llama y muestra la interfaz Main
     * @autor: Maria Martinez
     * @version: 20/11/23
     */
    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        /**
        * Descripcion: El main de la interfaz principal
        */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setTabla(tabla);
                main.setMonticulo(monticulo);
                main.setUsuarios(usuarios);
                main.setTiempo(tiempo);

                main.setVisible(true);
            }
        });

        // Ocultar esta interfaz
        this.setVisible(false);
    }//GEN-LAST:event_ReturnActionPerformed

    /**
     * Descripcion: Libera de la cola de impresion un documento para imprimirlo
     * @autor: Maria Martinez
     * @version: 20/11/23
     */
    private void LiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiberarActionPerformed
        if (!monticulo.IsEmpty()){
            String nombre = monticulo.Liberar();
            NodoUsuario usuario = usuarios.BuscarUsuario(nombre);
            usuarios.ChequearDoc(usuario.getNombreUsuario(), nombre, false);
            usuarios.Dead(usuario.getNombreUsuario());
            tabla.EliminarDoc(nombre, usuario.getNombreUsuario());
            MostrarColaPActionPerformed(evt);
            
        } else {
            JOptionPane.showMessageDialog(null, "\nLa cola de impresion esta vacia!");
        }
        
    }//GEN-LAST:event_LiberarActionPerformed

    /**
     * Descripcion: Muestra la cola de impresion como un arbol binario
     * @autor: Maria Martinez
     * @version: 20/11/23
     */
    private void MostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArbolActionPerformed
        if (!monticulo.IsEmpty()){
            monticulo.Show();
        } else {
            JOptionPane.showMessageDialog(null, "\nLa cola de impresion esta vacia!");
        }
    }//GEN-LAST:event_MostrarArbolActionPerformed
    
    /**
     * Descripcion: Muestra la cola de impresion en una tabla
     * @autor: Mauricio Mendez
     * @version: 20/11/23
     */
    public void MostrarColaPActionPerformed(java.awt.event.ActionEvent evt) {                                            
        int fila = tablaUsuarios.getRowCount();
        
        for (int i = fila-1; i >=0; i--) {
            modelo.removeRow(i);
        }
        
        if (monticulo.getSize() != 0){
            NodoMonticulo[] colaimpresion = monticulo.getCola();
            for (int i = 0; i < monticulo.getSize(); i++) {
                String nombredoc = colaimpresion[i].getNombreDocumento();
                String tipodoc = colaimpresion[i].getTipoDocumento();
                int tamañodoc = colaimpresion[i].getTamaño();

                modelo.addRow(new Object[]{nombredoc,tipodoc,tamañodoc });
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejoColaImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejoColaImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejoColaImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejoColaImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejoColaImpresion().setVisible(true);
            }
        });
    }

    public TablaDeDispersion getTabla() {
        return tabla;
    }

    public void setTabla(TablaDeDispersion tabla) {
        this.tabla = tabla;
    }

    public MonticuloBinario getMonticulo() {
        return monticulo;
    }

    public void setMonticulo(MonticuloBinario monticulo) {
        this.monticulo = monticulo;
    }
    
    
    public Usuarios getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public Cronometro getTiempo() {
        return tiempo;
    }

    public void setTiempo(Cronometro tiempo) {
        this.tiempo = tiempo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Liberar;
    private javax.swing.JButton MostrarArbol;
    private javax.swing.JButton Return;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
