/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


package colaimpresion;

import javax. swing.*;
import java.awt.*;
import java.awt.Font;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import javax. swing.JPanel;
import colaimpresion.BT;

/**
* Descripcion: JPanel donde utilizando metodos de Java se dibuja los nodos del monticulo
*              junto con sus relaciones, como un arbol
* @autor: Andrea Reyes
* @version: 24/11/23
*/
public class MostrarMonticulo extends JPanel {
    
        public MonticuloBinario bt; 
        
 
        /**
        * Descripcion: Constructor de la clase 
        * @autor: Andrea Reyes
        * @version: 24/11/23
        */
        public MostrarMonticulo(MonticuloBinario bt){
            this.bt=bt;
        }
        
        
        /**
        * Descripcion: Accede al fondo del JFrame y utilizando las primitivas graficas dibuja lineas y nodos
        * @autor: Andrea Reyes
        * @version: 24/11/23
        */
        @Override
        public void paint (Graphics g) {
            super.paint (g) ;
            Dibujar(g, 0,0, this.getWidth () -25, 100);

        }
        
        /**
        * Descripcion: Metodo recursivo que se encarga de dibujar cada nodo junto con el nombre de documento y su relacion
        * @autor: Andrea Reyes
        * @version: 24/11/23
        * @param index: Indice del nodo en el monticulo
        * @param g: Objeto de Graphics
        * @param x0: Coordenada
        * @param x1: Coordenada
        * @param y: Coordenada
        */
        public int Dibujar(Graphics g,int index,int x0, int x1,int y){
            String data =  bt.getCola()[index] .getNombreDocumento();
            g. setFont (new Font ("Tahoma", Font.BOLD, 20)) ;
            FontMetrics fm= g.getFontMetrics();
            int n = (x0+x1)/2;
            g. drawOval (n, y, 75, 30); // ajusta r!
            g. setFont (new Font ("Arial", Font. BOLD, 15)); 
            g.drawString (data, n+15, y+20);
            
            if (bt.tieneHijoDer(index)) {
                int hijoDer = bt.hijoDer(index);
                int x2 = Dibujar(g,hijoDer,n,x1,y+50);
                g.drawLine(n+25, y+30, x2+25, y+50);
                
              
            }
            
            if (bt.tieneHijoIzq(index)) {
                int hijoIzq = bt.hijoIzq(index);
                int x2 = Dibujar(g,hijoIzq,x0,n,y+50);
                g.drawLine(n+25, y+30, x2+25, y+50);
              
            }
            
            
            return n;
          
      
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
