package colaimpresion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MAURICIO MENDEZ
 */
public class VistaDocumentos extends javax.swing.JFrame {
    private Usuarios usuarios;
    private Documento [] documentos;
    private NodoUsuario usuario;
    private Cronometro tiempo = new Cronometro();
    DefaultTableModel modelo = new DefaultTableModel();
    private TablaDeDispersion tabla = new TablaDeDispersion();
    private MonticuloBinario monticulo = new MonticuloBinario();
    /**
     * Creates new form VistaDocumentos
     */
    public VistaDocumentos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        usuarios = new Usuarios();
        String info [] = {"Nombre","Tipo","Tamaño","Encolado"}; 
        modelo.setColumnIdentifiers(info);
        tablaUsuarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, -1));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 360, 320));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        jLabel1.setText("Documentos de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 400, 54));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen6.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /**
        * Descripcion: El main de la interfaz principal
        */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManejoDocumentos manejo = new ManejoDocumentos();
                manejo.setUsuarios(usuarios);
                manejo.setTabla(tabla);
                manejo.setMonticulo(monticulo);
                manejo.setTiempo(tiempo);
                manejo.LlenarboxActionPerformed(evt);
                manejo.LlenarboxSizeActionPerformed(evt);
                manejo.LlenarboxTiposActionPerformed(evt);
                manejo.setVisible(true);
            }
        });

        // Ocultar esta interfaz
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void LlenadoTabla(java.awt.event.ActionEvent evt){
        int fila = tablaUsuarios.getRowCount();

        for (int i = fila-1; i >=0; i--) {
            modelo.removeRow(i);
        }
        Documento[] documentos = usuario.getDocumentos();

        for (int i = 0; i < documentos.length; i++) {
            String nombredoc = documentos[i].getNombreDocumento();
            String tipodoc = documentos[i].getTipoDocumento();
            int tamañodoc = documentos[i].getTamaño();
            String encolado= "";
            if(documentos[i].isEncolado()==false){
                encolado = "No";
            }else{
                encolado = "Si";
            }
            modelo.addRow(new Object[]{nombredoc,tipodoc,tamañodoc,encolado });
        }
    }    
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public void setDocumentos(Documento[] documentos) {
        this.documentos = documentos;
    }

    public void setUsuario(NodoUsuario usuario) {
        this.usuario = usuario;
    }

    public void setTiempo(Cronometro tiempo) {
        this.tiempo = tiempo;
    }

    public void setTabla(TablaDeDispersion tabla) {
        this.tabla = tabla;
    }

    public void setMonticulo(MonticuloBinario monticulo) {
        this.monticulo = monticulo;
    }

    
    
    public Usuarios getUsuarios() {
        return usuarios;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
